### ISSUE TITLE
pack tests not working on 8.1.3

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#177]
Not sure why. Just making an issue on it for now.

![prebuild-tests-8 1 3](https://user-images.githubusercontent.com/308049/27985033-737abcb6-63e3-11e7-929b-b252e8162f90.png)

**Comment by mathiask88** [comment]
I would like to help, but all the tests are not that windows friendly :\ I think the behavior of `tar-stream` is also not consistent across platforms. I think we should change this because `prebuild` is intended to run on different platforms, isn't it?

**Comment by ralphtheninja** [comment]
> I think we should change this because prebuild is intended to run on different platforms, isn't it?

Or make `tar-stream` consistent on platforms :)

What's the difference?

cc @mafintosh

**Comment by ralphtheninja** [comment]
@mathiask88 Might have misunderstood you, in case you was referring to fixing tar-stream

**Comment by mathiask88** [comment]
This is the `pack-test.js` on windows and node 8.1.2
```
TAP version 13
# missing file calls back with error
ok 1 should error
# resulting file is a gzipped tar archive
ok 2 no output folder
ok 3 created output folder
ok 4 correct filename
ok 5 should be called
ok 6 correct tar path
not ok 7 correct filename
  ---
    operator: equal
    expected: |-
      'C:\\Users\\Mathias\\Documents\\GitHub\\prebuild\\test\\pack-test.js'
    actual: |-
      'C_/Users/Mathias/Documents/GitHub/prebuild/test/pack-test.js'
    at: Pack.tarStream.entry (C:\Users\Mathias\Documents\GitHub\prebuild\test\pack-test.js:69:9)
    stack: |-
      Error: correct filename
          at Test.assert [as _assert] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:212:54)
          at Test.bound [as _assert] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:64:32)
          at Test.equal.Test.equals.Test.isEqual.Test.is.Test.strictEqual.Test.strictEquals (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:347:10)
          at Test.bound [as equal] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:64:32)
          at Pack.tarStream.entry (C:\Users\Mathias\Documents\GitHub\prebuild\test\pack-test.js:69:9)
          at C:\Users\Mathias\Documents\GitHub\prebuild\pack.js:18:30
          at FSReqWrap.oncomplete (fs.js:153:5)
  ...
ok 8 .size is set
ok 9 .mode is set
not ok 10 .gid is set
  ---
    operator: ok
    expected: true
    actual:   0
    at: Pack.tarStream.entry (C:\Users\Mathias\Documents\GitHub\prebuild\test\pack-test.js:72:9)
  ...
not ok 11 .uid is set
  ---
    operator: ok
    expected: true
    actual:   0
    at: Pack.tarStream.entry (C:\Users\Mathias\Documents\GitHub\prebuild\test\pack-test.js:73:9)
  ...
ok 12 correct filename
not ok 13 piping to correct stream
  ---
    operator: deepEqual
    expected: |-
      undefined
    actual: |-
      { _buffer: <Buffer 80 14 11 e2 a4 01 00 00 50 e4 12 e4 a4 01 00 00 48 40 00 00 00 00 00 00 9d 13 00 00 0c 00 00 00 83 00 00 00 00 00 00 00 b0 ba 11 e4 a4 01 00 00 d0 ba ... >, _chunkSize: 16384, _events: { end: [ [Function: bound onceWrapper], [Function: bound onceWrapper] ], prefinish: [Function: bound onceWrapper] }, _eventsCount: 2, _finishFlushFlag: 4, _flushFlag: 0, _hadError: false, _handle: { onerror: [Function: bound zlibOnError] }, _level: -1, _maxListeners: undefined, _offset: 0, _opts: {}, _readableState: { awaitDrain: 0, buffer: { head: null, length: 0, tail: null }, decoder: null, defaultEncoding: 'utf8', destroyed: false, emittedReadable: false, encoding: null, endEmitted: false, ended: false, flowing: null, highWaterMark: 16384, length: 0, needReadable: true, objectMode: false, pipes: null, pipesCount: 0, readableListening: false, reading: false, readingMore: false, resumeScheduled: false, sync: false }, _strategy: 0, _transformState: { afterTransform: [Function], needTransform: false, transforming: false, writecb: null, writechunk: null, writeencoding: null }, _writableState: { bufferProcessing: false, bufferedRequest: null, bufferedRequestCount: 0, corked: 0, corkedRequestsFree: { entry: null, finish: [Function: bound onCorkedFinish], next: null }, decodeStrings: true, defaultEncoding: 'utf8', destroyed: false, ended: false, ending: false, errorEmitted: false, finalCalled: false, finished: false, highWaterMark: 16384, lastBufferedRequest: null, length: 0, needDrain: false, objectMode: false, onwrite: [Function: bound onwrite], pendingcb: 0, prefinished: false, sync: true, writecb: null, writelen: 0, writing: false }, allowHalfOpen: true, bytesRead: 0, domain: null, readable: true, writable: true }
    at: Pack.tarStream.pipe (C:\Users\Mathias\Documents\GitHub\prebuild\test\pack-test.js:79:9)
    stack: |-
      Error: piping to correct stream
          at Test.assert [as _assert] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:212:54)
          at Test.bound [as _assert] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:64:32)
          at Test.deepEqual.Test.deepEquals.Test.isEquivalent.Test.same (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:380:10)
          at Test.bound [as deepEqual] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:64:32)
          at Pack.tarStream.pipe (C:\Users\Mathias\Documents\GitHub\prebuild\test\pack-test.js:79:9)
          at C:\Users\Mathias\Documents\GitHub\prebuild\pack.js:30:17
          at FSReqWrap.oncomplete (fs.js:153:5)
  ...
ok 14 should be called
ok 15 no error
ok 16 file created
not ok 17 plan != count
  ---
    operator: fail
    expected: 17
    actual:   15
    stack: |-
      Error: plan != count
          at Test.assert [as _assert] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:212:54)
          at Test.bound [as _assert] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:64:32)
          at Test.fail (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:277:10)
          at Test.bound [as fail] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:64:32)
          at Test._exit (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:172:14)
          at Test.bound [as _exit] (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\lib\test.js:64:32)
          at process.<anonymous> (C:\Users\Mathias\Documents\GitHub\prebuild\node_modules\tape\index.js:86:19)
          at emitOne (events.js:115:13)
          at process.emit (events.js:210:7)
  ...

1..17
# tests 17
# pass  12
# fail  5

```

I did not look deep into it, but the filename looks odd. The uid and gid should be handled by the test I think.

**Comment by mathiask88** [comment]
Ahh ok, the filename is from this line https://github.com/mafintosh/prebuild/blob/master/pack.js#L19. So `tar-stream` is just fine, sorry

**Comment by mathiask88** [comment]
@ralphtheninja The pack-test is failing because in node.js v8 the zlib functions are set with `defineProperty()` and are configurable but not writable. So the assignment operator that monkey patches the `createGzip` function does nothing at all and `gzipStream = _createGzip()` never gets called.

So something like `if (Object.defineProperty) Object.defineProperty(zlib, 'createGzip', {writable: true})` should do the trick. Or just define the value instead of make it writable, there are more solutions.

**Comment by ralphtheninja** [comment]
@mathiask88 Mind making a PR? :)

**Comment by mathiask88** [comment]
@ralphtheninja sure :)

**Comment by mathiask88** [comment]
@ralphtheninja BTW strict mode would have made this very easy to find :)
