### ISSUE TITLE
version.replace is not a function

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#25]
I was trying out `prebuild` for leveldown and got the following error:

```
prebuild info build Prebuild written to prebuilds/leveldown-v1.4.1-node-v44-linux-x64.tar.gz
prebuild info build Preparing to prebuild leveldown@1.4.1 for v3.0.0 on linux-x64
prebuild http request https://iojs.org/dist/v3.0.0/iojs-v3.0.0.tar.gz
prebuild http 200 https://iojs.org/dist/v3.0.0/iojs-v3.0.0.tar.gz
prebuild info install node-gyp should now work for v3.0.0
/home/lms/src/prebuild/abi.js:6
  version = version.replace('v', '')
                    ^
TypeError: version.replace is not a function
    at getAbi (/home/lms/src/prebuild/abi.js:6:21)
    at /home/lms/src/prebuild/abi.js:22:7
    at /home/lms/src/prebuild/node_modules/node-gyp-install/index.js:56:13
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I re-ran the command and then it worked. I'm wondering if it's related to requesting `https://iojs.org/dist/v3.0.0/iojs-v3.0.0.tar.gz`.

**Comment by ralphtheninja** [comment]
Yes! I can reproduce this by removing `~/.node-gyp/3.0.0` :)

**Comment by ralphtheninja** [comment]
Fix coming. This is obviously related to my refactorings. Adding test for it.
