### ISSUE TITLE
Problem: -pb switch causes prebuild to crash

### ISSUE THREAD

**Issue by hintjens** [mafintosh/prebuild#88]
```
nodejs> prebuild -pb 4.2.4
/home/ph/.nvm/v5.5.0/lib/node_modules/prebuild/node_modules/graceful-fs/polyfills.js:18
  chdir.call(process, d)
        ^

TypeError: Bad argument.
    at TypeError (native)
    at process.chdir (/home/ph/.nvm/v5.5.0/lib/node_modules/prebuild/node_modules/graceful-fs/polyfills.js:18:9)
    at Object.<anonymous> (/home/ph/.nvm/v5.5.0/lib/node_modules/prebuild/bin.js:21:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by mafintosh** [comment]
Fixed in 3.0.2
